/* ═══════════════════════════════════════════════════════════════
   main.c  –  Entry point for the Bank Fraud Detection DSL.

   Usage:
       ./fraud_engine <rules_file> <transactions_csv>

   Example:
       ./fraud_engine samples/rules.txt samples/transactions.csv
   ═══════════════════════════════════════════════════════════════ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "engine.h"

/* Declared in parser.tab.c (generated by Bison) */
extern int   yyparse(void);
extern void  yyset_in(FILE *f);
extern RuleList g_rulelist;

int main(int argc, char *argv[]) {

    printf("\n╔══════════════════════════════════════════════════════╗\n");
    printf("║      Bank Fraud Detection DSL  — v1.0               ║\n");
    printf("║      Compiler Design Project  (Lex + Yacc)          ║\n");
    printf("╚══════════════════════════════════════════════════════╝\n\n");

    if (argc != 3) {
        fprintf(stderr, "Usage: %s <rules_file> <transactions_csv>\n\n", argv[0]);
        fprintf(stderr, "  rules_file        : path to your .txt rule file\n");
        fprintf(stderr, "  transactions_csv  : path to the transactions CSV\n\n");
        fprintf(stderr, "Example:\n");
        fprintf(stderr, "  %s samples/rules.txt samples/transactions.csv\n\n", argv[0]);
        return 1;
    }

    const char *rules_path = argv[1];
    const char *csv_path   = argv[2];

    /* ── Open rule file ── */
    FILE *rule_file = fopen(rules_path, "r");
    if (!rule_file) {
        fprintf(stderr, "Error: Cannot open rules file '%s'\n", rules_path);
        return 1;
    }

    /* ── Parse rules through Lex + Yacc ── */
    printf("Loading rules from: %s\n", rules_path);
    printf("─────────────────────────────────────────────────\n");

    yyset_in(rule_file);
    memset(&g_rulelist, 0, sizeof(g_rulelist));

    int parse_result = yyparse();
    fclose(rule_file);

    if (parse_result != 0) {
        fprintf(stderr, "\nFailed to parse rules file. Please fix the errors above.\n");
        return 1;
    }

    printf("\n✅ Parsed %d rule(s) successfully.\n", g_rulelist.count);

    /* ── Run engine against transactions ── */
    run_engine(&g_rulelist, csv_path);

    /* ── Cleanup ── */
    free_rule_list(&g_rulelist);

    return 0;
}
